In [1]:
import numpy as np

In [2]:
size=6
no_of_emp=size//2
pop=np.empty((no_of_emp,3))

for i in range(pop.shape[0]):
    for j in range(pop.shape[1]):
        pop[i,j]=0+np.random.random((1,))*(8-0)
print(pop)

[[0.52447617 2.55571107 6.10309599]
 [4.64333966 5.23212927 4.10635961]
 [6.56174129 5.34395771 3.6376383 ]]


In [3]:
def objective(pop):
    f=[]
    for i in range(pop.shape[0]):
        f.append(pop[i,0]**2+pop[i,1]**2+pop[i,2]**2)
    return f

def fitness(pop):
    o=objective(pop)
    fit=[]
    for i in o:
        if(i<0):
            fit.append(1-i)
        else:
            fit.append(1/(1+i))
    return fit
best=pop[np.argmax(fitness(pop)),:]
trial=[0]*pop.shape[0]
print(pop)
print(fitness(pop))
print(best)
print(trial)

[[0.52447617 2.55571107 6.10309599]
 [4.64333966 5.23212927 4.10635961]
 [6.56174129 5.34395771 3.6376383 ]]
[0.022195333829636822, 0.014970515031108907, 0.011648665284082727]
[0.52447617 2.55571107 6.10309599]
[0, 0, 0]


In [6]:
import random
def employee(pop,fit,lb,up,trial,no_of_emp):
    for i in range(3):
        p=random.randint(0,2)
        while(i==p):
            p=random.randint(0,2)
        j=random.randint(0,pop.shape[1]-1)
        new=pop[i,j]+np.random.uniform(low=-1,high=1,size=(1,))*(pop[i,j]-pop[p,j])
        if(new<lb):
            new=lb
        if(new>up):
            new=up
        x_new=np.array([pop[i,:].copy()])
        x_new[0,j]=new
        f=fitness(x_new)
        if(f>fit[i]):
            pop[i,:]=x_new[:]
            trial[i]=0
        else:
            trial[i]=trial[i]+1
    return pop

print(employee(pop,fitness(pop),0,8,trial,no_of_emp))
print(trial)

[[0.52447617 2.22378192 6.10309599]
 [4.64333966 5.23212927 3.89039145]
 [6.56174129 5.34395771 3.6376383 ]]
[0, 0, 1]


In [7]:
fit=fitness(pop)
prob=[]
for i in fit:
    prob.append(0.9*(i/max(fit))+0.1)
print(prob)

[1.0, 0.701209456610565, 0.5557104135609906]


In [9]:
def onlooker(prob,pop,lb,up,trial,fit,no_of_emp):
    i=0
    for _ in range(no_of_emp):
        r=random.random()
        if(i==3):
            i=0
        if(r<prob[i]):
            p=random.randint(0,2)
            while(i==p):
                p=random.randint(0,2)
            j=random.randint(0,pop.shape[1]-1)
            new=pop[i,j]+np.random.uniform(low=-1,high=1,size=(1,))*(pop[i,j]-pop[p,j])
            if(new<lb):
                new=lb
            if(new>up):
                new=up
            x_new=np.array([pop[i,:].copy()])
            x_new[0,j]=new
            f=fitness(x_new)
            if(f>fit[i]):
                pop[i,:]=x_new[:]
                trial[i]=0
            else:
                trial[i]=trial[i]+1
            i=i+1
        else:
            i=i+1
    return pop
print(onlooker(prob,pop,0,8,trial,fit,no_of_emp))
print(trial)

[[0.51949356 2.22378192 6.10309599]
 [3.1141468  5.23212927 3.89039145]
 [6.56174129 5.34395771 3.6376383 ]]
[0, 0, 1]
